### ISSUE TITLE
__init__() got an unexpected keyword argument 'log_level'

### ISSUE THREAD

**Issue by Wangpeiyi9979** [xiaolinAndy/CSDS#13]
Hi, thanks for your nice work.
When I run the PGN model, I meet two euros as follow:

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/42565075/142993871-6cda0263-7fdb-45c3-9526-42320fd002ba.png">

could your help me?
Thanks a lot!!

**Comment by xiaolinAndy** [comment]
第一个错误应该是由于files2rouge安装步骤错误导致的。如果无法使用files2rouge的话也可以自行换成其他的rouge计算方法。
第二个是否是因为没有成功保存相应的checkpoint呢？

**Comment by Wangpeiyi9979** [comment]
确实是files2rouge的问题，感谢您
