### ISSUE TITLE
tencent embedding的更多细节

### ISSUE THREAD

**Issue by offrande** [xiaolinAndy/CSDS#15]
您好，截止目前，TX提供的version v0.2.0一共有四个版本。
Dimension 200   /  small |  Large
Dimension 100  /   small |  Large
请问您实际使用的是哪个版本？

**Comment by xiaolinAndy** [comment]
我们使用的是v0.1.0

**Comment by offrande** [comment]
谢谢回复。 再打扰一下，你们实际运行的硬件是什么GPU，用了几张卡？

**Comment by offrande** [comment]
> 我们使用的是v0.1.0

我下载了v0.1.0，解压后的实际大小有15.5G。  而我在你们的CSDS/models/Fast-RL/data_utils/embeddings 中发现了一个 dialogue_embed_word，仅有41MB， 请问我是直接用你们github中的词嵌入（41M），还是替换成TX的15G

**Comment by xiaolinAndy** [comment]
我们使用的是TITANX和RTX3090，单卡运行即可，详细介绍请参考论文附录部分。您可以直接用我们github中的词嵌入，也可以替换成TX的15G然后重新生成词嵌入
