### ISSUE TITLE
如何使用"intent"字段

### ISSUE THREAD

**Issue by zhaokanghuiasd** [xiaolinAndy/CSDS#17]
作者您好：

在csds数据集中有”intent“字段，但论文中和代码中好像没有看到对其相关的使用，请问这方面有可以参考的内容吗

**Comment by xiaolinAndy** [comment]
intent就是论文中提到的每个摘要对应的topic，我们在后续工作中使用了该信息，该文章还在审稿中，您也可以根据需求自行使用该信息。
