### ISSUE TITLE
关于CSDS数据集问题

### ISSUE THREAD

**Issue by jeremy110** [xiaolinAndy/CSDS#19]
感谢大佬的git，我这里训练完TDS+SATM*，想请问一下几个数据集的问题

1.rouge-f的分数有些可以高到0.7879/0.6517/0.7220，但有些低到只有0.3947/0.1647/0.3926，比较两个对话，分数低的turn较多，所以turn越多效果会越差? 还是有其他原因?
2.承1 turn太多有些是這樣
     (26) 【客户】 你 们 已 经 有 邮 件 告 诉 我 了 
     (27) 【客户】 就 是 告 诉 我 在 清 关 
     (28) 【客户】 你 们 不 告 诉 怎 么 清 关 
     (29) 【客户】 让 我 做 什 么 也 不 说 
     (30) 【客户】 然 后 又 是 一 个 礼 拜 过 去 了 
     (31) 【客户】 我 也 是 有 耐 心 的 
从26~31都是客户，感觉有些turn是可以合并的，如果合并是否能提升效果?
或是有什么办法改善这种对话数据?

**Comment by xiaolinAndy** [comment]
1. 是的，我们训练的结果也发现对话越长效果越差。因为这样的对话输入信息量更多，提取关键信息的难度也会更大。
2. 我们没有实验合并后是否会提升效果，您可以自行尝试一下。但我们认为效果不会有太大变化，因为总的输入信息基本是一样的。

**Comment by jeremy110** [comment]
感謝您的回覆，我會再嘗試一下

**Comment by jeremy110** [comment]
大佬想再请问一下，我在做上述所说的合并当中发现，我多加一个标点符号(如下图)，没想到预测的结果会有差异。
想请问是不是因为原始数据当中，有些句子当中有标点符号而有些没有，进而影响到最终预测结果?
![messageImage_1664433402741](https://user-images.githubusercontent.com/52516810/192957174-cf209e41-cd39-4df0-820a-9d2778f7b275.jpg)

**Comment by xiaolinAndy** [comment]
是的，但也不一定完全是标点符号的原因，毕竟网络每一次训练都不是一模一样的

**Comment by jeremy110** [comment]
好的 谢谢
