### ISSUE TITLE
TDS-SATM遇到的问题

### ISSUE THREAD

**Issue by llt1836** [xiaolinAndy/CSDS#20]
你好，在运行TDS-SATM程序时遇到了这样的问题，可以帮看下怎么解决么。
![2022-10-19 18-33-41 的屏幕截图](https://user-images.githubusercontent.com/71361327/196667873-6d63621d-cbc4-47c4-bbba-22bff1147b29.png)

**Comment by xiaolinAndy** [comment]
请问你是按照readme里面的步骤执行的么，看下数据集和预训练BERT有没有放对位置，然后run.sh脚本中的代码一行一行执行，看看是哪一行报错了

**Comment by llt1836** [comment]
亲~     岚婷已经收到了你的邮件啦~会尽快给您回复的~辛苦啦！                                                                                            谢谢~
