### ISSUE TITLE
No such file or directory: '/home/mz20/CSDS/models/BERT/logs/bert_abs_test_final.log'

### ISSUE THREAD

**Issue by pony-m** [xiaolinAndy/CSDS#9]
Instruction for BERT (BERTExt/BERTAbs)
1.Go to the models/BERT/ directory.
2.Download the CSDS dataset, create a new folder named data/ and put CSDS under the data/ folder.
3.Download the pretrained BERT model, create a new folder named bert_base_chinese/ and put it into the bert_base_chinese/ folder.
4.Run the bash file run.sh to train and test.

请问，报错应该是与step 3有较大的关系吧，怎样下载？到哪里下载？

**Comment by xiaolinAndy** [comment]
可以去huggingface的官网（https://huggingface.co/）下载bert_base_chinese的模型

**Comment by pony-m** [comment]
感谢回复~可是下载下来后并没有logs文件夹



| |
马正
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月12日 20:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [xiaolinAndy/CSDS] No such file or directory: '/home/mz20/CSDS/models/BERT/logs/bert_abs_test_final.log' (Issue #9) |

可以去huggingface的官网（https://huggingface.co/）下载bert_base_chinese的模型

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaolinAndy** [comment]
这个log是你需要正常跑完脚本才能得到的，你可以看下是脚本里面哪一步报错了。或者新建一个log文件夹看看是否还有相同的错误
